---
name: Release Binary

on:
  release:
    types: [created]

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      -
        name: Parse tag
        id: tag
        run: |
          COMMIT := $(shell git log -1 --format='%H')
          echo "COMMIT" >> $GITHUB_ENV

      - name: Release
        uses: wangyoucao577/go-release-action@v1      
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          asset_name: centaurid
          sha256sum: TRUE
          build_flags: -tags "netgo ledger"
          ldflags: -X github.com/cosmos/cosmos-sdk/version.Name=centauri 
                    -X github.com/cosmos/cosmos-sdk/version.AppName=centaurid 
                    -X github.com/cosmos/cosmos-sdk/version.Version=${{ env.APP_VERSION }}
                    -X github.com/cosmos/cosmos-sdk/version.Commit=${{github.COMMIT}}
                    -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo ledger" 
                    -w -s