---
name: Release Binary

on:
  release:
    types: [created]

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker compose
        run: docker-compose up -d

      - name: Copy binary
        run: docker cp composable-centauri-node-1:/usr/bin/centaurid ./centaurid

      - name: Save sha256 sum
        run: sha256sum ./centaurid > ./centaurid_sha256.txt

      - name: Release
        uses: softprops/action-gh-release@v1        
        with:
          token: ${{ github.token }}
          files: |
            centaurid
            centaurid_sha256.txt

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2